[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
custom_apl = "2rtmSEY3TG51Qxb34Fq5LB4XTqdAzTwNKrD333ysb1ia"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/cenwadike/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
